export const REMOVE_CONNECTION = 'REMOVE_CONNECTION'
export const ADD_CONNECTION = 'ADD_CONNECTION'

export const GET_SETTINGS = 'SET_AGENTS'
export const SET_SETTINGS = 'SET_CURRENT_AGENT'

export const SET_CURRENT_CONNECTION = 'SET_CURRENT_CONNECTION'
export const SET_CONNECTIONS = 'SET_CONNECTIONS'

