export const REMOVE_CONNECTION = 'REMOVE_CONNECTION'
export const ADD_CONNECTION = 'ADD_CONNECTION'

export const GET_SETTINGS = 'SET_AGENTS'
export const SET_SETTINGS = 'SET_CURRENT_AGENT'

export const SET_CURRENT_CONNECTION = 'SET_CURRENT_CONNECTION'
export const SET_CONNECTIONS = 'SET_CONNECTIONS'

export const SET_STORE_CURRENT_QUERY_RESULT = 'SET_STORE_CURRENT_QUERY_RESULT'
export const SET_STORE_CURRENT_START_INDEX = 'SET_STORE_CURRENT_START_INDEX'
export const SET_STORE_CURRENT_ITEM = 'SET_STORE_CURRENT_ITEM'
export const SET_STORE_INFO = 'SET_STORE_INFO'
export const APPLY_REMOVE_ITEM = 'APPLY_REMOVE_ITEM'

